project:
  type: website
  output-dir: docs
  
website:
  title: "Electoral Commission Pre-Election Data"
  navbar:
    left:
      - href: index.qmd
        text: "January - May 2024"
    tools:
      - icon: github
        href: https://github.com/hazelcgordon/campaign_donation_tracker
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2024, Electoral Reform Society"

format:
  html:
    theme: cerulean
    toc: true

editor: source

