---
title: ""
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries, warning=FALSE, include=FALSE}

library(tidyverse)
library(ggplot2)
library(plotly)

```

## Donations: April/May 2024 period

```{r, include=FALSE}

may2024 <- read.csv("donor_may2024.csv")

#columns of interest

may2024 <- may2024 %>%
  select(AcceptedDate, ReceivedDate, ReportingPeriodName, RegulatedEntityName, RegulatedDoneeType, Value, DonorName, DonorStatus, Postcode, DonationType, NatureOfDonation, PurposeOfVisit)

```

```{r associatied political party, include=FALSE}

#creating a new column for associated political party

labour_names <- c("Andy Burnham", "Steve Rotheram", "Wes Streeting", "Labour To Win", "Dan Jarvis MP", "Labour Together", "Labour Campaign For Electoral Reform", "Michael Shanks", "Ms Kim Leadbeater", "Emma Hardy", "Kim McGuinness", "Rachel Reeves MP", "The Rt Hon David Lammy MP", "Dr Olivia Blake", "Mr Grahame Morris MP", "Ms Diana Ruth Johnson MP", "Mr Navendu Mishra", "Andrew Western", "Sharon Hodgson MP", "Mr Damien Egan", "Mr Steve McCabe", "Ruth Jones", "Anna McMorrin")

conservative_names <- c("Carlton Club Political Committee", "Mr Jonathan Gullis", "Simon Hart MP", "The Rt Hon Dr Liam Fox MP", "Alan Mak MP", "Mr Darren Millar", "Samuel Rowlands", "Russell George", "Simon Clarke", "Ms Caroline Nokes", "Suella Braverman", "Mr Steve Barclay", "Mr Nicholas John Gibb MP", "Mr Alun Cairns MP", "Mr Bim Afolami", "Lucy Frazer MP", "Mr Andy Street", "David Simmonds")

libdem_names <- c("Mr Tim Farron MP")

DUP_names <- c("Jim Shannon")

#mapping political party associations onto names

may2024 <- may2024 %>%
  mutate(PartyAffiliation = case_when(
    RegulatedEntityName %in% labour_names ~ "Labour",
    RegulatedEntityName %in% conservative_names ~ "Conservative",
    RegulatedEntityName %in% libdem_names ~ "Lib Dem",
    RegulatedEntityName %in% DUP_names ~ "DUP",
    TRUE ~ NA_character_  # Default to NA if no match
  ))

#re-order columns 

may2024 <- may2024 %>%
  select(AcceptedDate, ReceivedDate, ReportingPeriodName, RegulatedEntityName, PartyAffiliation, RegulatedDoneeType, Value, DonorName, DonorStatus, Postcode, DonationType, NatureOfDonation, PurposeOfVisit)

```

### How much money did each party recieve, and how was this associated with the status of the donor?

```{r echo=FALSE, warning=FALSE, fig.align='center'}

# Remove £ sign and convert to numeric
may2024$Value <- as.numeric(gsub("[£,\"]", "", may2024$Value))

#set factor levels

may2024$PartyAffiliation <- factor(may2024$PartyAffiliation, levels = c("Conservative", "Labour", "Lib Dem", "DUP"))

may2024$DonorStatus <- factor(may2024$DonorStatus, levels = c("Registered Political Party", "Trade Union", "Company", "Individual", "Unincorporated Association", "Other"))

# Create a complete data frame with all combinations of DonorStatus and PartyAffiliation
complete_data <- expand.grid(PartyAffiliation = 
                              levels(may2024$PartyAffiliation), 
                             DonorStatus = unique(may2024$DonorStatus)
                             )

#create summary

donorstatus_summary <- may2024 %>%
  group_by(PartyAffiliation, DonorStatus) %>%
  summarize(TotalValue = sum(Value, na.rm = TRUE), .groups = 'drop') %>%
  right_join(complete_data, by = c("PartyAffiliation", "DonorStatus")) %>%
  replace_na(list(TotalValue = 0))

# Add a formatted value column for hover text
donorstatus_summary <- donorstatus_summary %>%
  mutate(HoverText = paste0("Total Value: £", format(TotalValue, big.mark = ",", scientific = FALSE), "<br>",
                            "Donor Status: ", DonorStatus, "<br>",
                            "Party Affiliation: ", PartyAffiliation))

#custom colours

custom_colors <- c("Registered Political Party" = "#1f78b4", "Trade Union" = "#e31a1c", "Company" = "#ff7f00", "Individual" = "#6a3d9a", "Unincorporated Association" = "#b2df8a", "Other" = "#FFD700")

# Create the base plot
donorstatus_p <- ggplot(donorstatus_summary, aes(x = PartyAffiliation, y = TotalValue, fill = DonorStatus, text = HoverText)) +
  geom_bar(stat = "identity", position = position_dodge2(preserve = "single"), width = 0.7) +
  scale_y_continuous(labels = scales::dollar_format(prefix = "£")) +
  scale_fill_manual(values = custom_colors) +
  labs(title = "",
       x = "",
       y = "") +
  theme_minimal() +
  theme(legend.position = "bottom",
        legend.title = element_blank(),
        legend.text = element_text(size = 8),
        legend.margin = margin(t = 10),
        legend.key.size = unit(0.5, "lines"))

#changing the hover info

donorstatus_int <- ggplotly(donorstatus_p, tooltip = c("text"))

#customisation

donorstatus_int <- donorstatus_int %>%
  layout(
    legend = list(
      title = list(text = NULL),  # Remove the legend title
      orientation = "h",          # Horizontal legend
      x = 0.5,                    # Centered horizontally
      xanchor = "center",         # Center the legend
      y = -0.2,                   # Position below the plot
      yanchor = "top",            # Align to the top
      font = list(size = 10),     # Adjust legend font size
      itemwidth = 30              # Adjust the width of legend items
    ),
       annotations = list(
      x = 1,                      # Position on the right
      y = 1,                   # Position below the legend
      text = "Source: Electoral Commission 2024 Donations Data",  
      showarrow = FALSE,          # No arrow
      xref = 'paper',             # Relative to the plotting area
      yref = 'paper',             # Relative to the plotting area
      xanchor = 'right',          # Align text to the right
      yanchor = 'top',           # Automatic vertical alignment
      font = list(size = 10)      # Adjust annotation font size
    )
  )


donorstatus_int

```

### What type of entities recieved the donation within each party?

```{r echo=FALSE}

#set factor levels

may2024$RegulatedDoneeType <- factor(may2024$RegulatedDoneeType, levels = c("MP - Member of Parliament", "Mayor", "Members Association", "Senedd Member"))


# Create a complete data frame with all combinations of Donortype and PartyAffiliation
complete_data <- expand.grid(PartyAffiliation = 
                              levels(may2024$PartyAffiliation), 
                             RegulatedDoneeType = 
                               unique(may2024$RegulatedDoneeType)
                             )

#create summary

doneetype_summary <- may2024 %>%
  group_by(PartyAffiliation, RegulatedDoneeType) %>%
  summarize(TotalValue = sum(Value, na.rm = TRUE), .groups = 'drop') %>%
  right_join(complete_data, by = c("PartyAffiliation", 
                                   "RegulatedDoneeType")) %>%
  replace_na(list(TotalValue = 0))

# Add a formatted value column for hover text
doneetype_summary <- doneetype_summary %>%
  mutate(HoverText = paste0("Total Value: £", format(TotalValue, big.mark = ",", scientific = FALSE), "<br>",
                            "Donee Type: ", RegulatedDoneeType, "<br>",
                            "Party Affiliation: ", PartyAffiliation))

#custom colours

type_colors <- c("MP - Member of Parliament" = "#1f78b4", "Mayor" = "#6a3d9a", "Members Association" = "#ff7f00", "Senedd Member" = "#b2df8a")

# Create the base plot
doneetype_p <- ggplot(doneetype_summary, aes(x = PartyAffiliation, y = TotalValue, fill = RegulatedDoneeType, text = HoverText)) +
  geom_bar(stat = "identity", position = position_dodge2(preserve = "single"), width = 0.7) +
  scale_y_continuous(labels = scales::dollar_format(prefix = "£")) +
  scale_fill_manual(values = type_colors) +
  labs(title = "",
       x = "",
       y = "") +
  theme_minimal() +
  theme(legend.position = "bottom",
        legend.title = element_blank(),
        legend.text = element_text(size = 8),
        legend.margin = margin(t = 10),
        legend.key.size = unit(0.5, "lines"))

#changing the hover info

doneetype_int <- ggplotly(doneetype_p, tooltip = c("text"))

#customisation

doneetype_int <- doneetype_int %>%
  layout(
    legend = list(
      title = list(text = NULL),  # Remove the legend title
      orientation = "h",          # Horizontal legend
      x = 0.5,                    # Centered horizontally
      xanchor = "center",         # Center the legend
      y = -0.2,                   # Position below the plot
      yanchor = "top",            # Align to the top
      font = list(size = 10),     # Adjust legend font size
      itemwidth = 30              # Adjust the width of legend items
    ),
       annotations = list(
      x = 1,                      # Position on the right
      y = 1,                   # Position below the legend
      text = "Source: Electoral Commission 2024 Donations Data",  
      showarrow = FALSE,          # No arrow
      xref = 'paper',             # Relative to the plotting area
      yref = 'paper',             # Relative to the plotting area
      xanchor = 'right',          # Align text to the right
      yanchor = 'top',           # Automatic vertical alignment
      font = list(size = 10)      # Adjust annotation font size
    )
  )


doneetype_int


```

### Was the purpose of the donation disclosed?

```{r echo=FALSE}

# Iterate over the rows and update NatureOfDonation based on DonationType
for (i in 1:nrow(may2024)) {
  if (may2024$DonationType[i] == "Visit") {
    may2024$NatureOfDonation[i] <- "Visit"
  }
}

#fill empty cells with 'undisclosed'

for (i in 1:nrow(may2024)) {
  if (may2024$NatureOfDonation[i] == "") {
    may2024$NatureOfDonation[i] <- "Undisclosed"
  }
}

#set factor levels

may2024$NatureOfDonation <- factor(may2024$NatureOfDonation, levels = c("Undisclosed", "Staff costs", "Administration services", "Consultancy services", "Visit"))

#group donor status by disclosure of purpose

donor_status_percent <- may2024 %>%
  group_by(DonorStatus, NatureOfDonation) %>%
  summarise(Count = n(), .groups = 'drop') %>%
  group_by(DonorStatus) %>%
  mutate(Percentage = Count / sum(Count) * 100) %>%
  ungroup()

#altering display of x-axis labels

donor_status_percent <- donor_status_percent %>%
  mutate(DonorStatus = case_when(
    DonorStatus == "Unincorporated Association" ~ "Unincorporated\n Association",
    TRUE ~ DonorStatus
  ))

donor_status_percent <- donor_status_percent %>%
  mutate(DonorStatus = case_when(
    DonorStatus == "Registered Political Party" ~ "Registered\n Political Party",
    TRUE ~ DonorStatus
  ))

#re-order factor

donor_status_percent <- donor_status_percent %>%
  mutate(DonorStatus = factor(DonorStatus, levels = c("Registered\n Political Party", "Trade Union", "Company", "Individual", "Unincorporated\n Association", "Other")))

# Add a formatted value column for hover text
donor_status_percent <- donor_status_percent %>%
  mutate(HoverText = paste0("Total Frequency: ", format(Count), "<br>",
                            "Percentage: ", sprintf("%.1f", Percentage), 
                            "<br>",
                            "Donor Status: ", DonorStatus, "<br>",
                            "Nature of Donation: ", NatureOfDonation))

#create a stacked bar chart plot

status_colors <- c("Undisclosed" = "#1f78b4", "Staff costs" = "#6a3d9a", "Administration services" = "#ff7f00", "Consultancy services" = "#b2df8a", "Visit" = "lightyellow")

nature_p <- ggplot(donor_status_percent, aes(x = DonorStatus, y = Percentage, fill = NatureOfDonation, text = HoverText)) +
  geom_bar(stat = "identity", position = "fill") +
  scale_y_continuous(labels = scales::percent) +
  scale_fill_manual(values = status_colors) +
  labs(title = "",
       x = "",
       y = "",
       fill = "") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

#interactive plot

nature_int <- ggplotly(nature_p, tooltip = c("text"))

#customisation

nature_int <- nature_int %>%
  layout(
    legend = list(
      title = list(text = NULL),  # Remove the legend title
      orientation = "v",          # Vertical legend
      x = 1.02,                   
      xanchor = "left",           # Align to the left
      y = 0.5,                    # Center vertically
      yanchor = "middle",         # Align to the middle
      font = list(size = 10),     # Adjust legend font size
      itemwidth = 30),
    margin = list(r = 120),       
    annotations = list(
      list(
        x = 1,                      # Position on the right
        y = -0.3,                   # Position below the legend
        text = "Source: Electoral Commission 2024 Donations Data",  
        showarrow = FALSE,          # No arrow
        xref = 'paper',             # Relative to the plotting area
        yref = 'paper',             # Relative to the plotting area
        xanchor = 'right',          # Align text to the right
        yanchor = 'auto',           # Automatic vertical alignment
        font = list(size = 10)      # Adjust annotation font size
      )
    )
  )

nature_int

```

