---
title: "Pre-poll 2024"
---

```{r include=FALSE}

library(tidyverse)
library(knitr)
library(kableExtra)

```

```{r functions, include=FALSE}

# remove blank spaces between £ sign and numbers for better table formatting

remove_spaces <- function(df) {
  df %>%
    mutate(across(everything(), ~ gsub("£\\s+", "£", .)))
}

# change 0's to blank cells

replace_pound_zero <- function(df) {
  df %>%
    mutate(across(everything(), ~replace(., . == "£0", "")))
}

```

### Totals: 2024 pre-poll week one and two

```{r processing data, include=FALSE}

pp2024 <- read.csv("data2024/prepoll1_2024.csv")
pp2024_2 <- read.csv("data2024/prepoll2_2024.csv")

#combine

pp2024 <- rbind(pp2024, pp2024_2)

#removing public fund money

pp2024 <- pp2024 %>%
  filter(!DonorStatus == "Public Fund")

#combining the Labour and Cooperative party

pp2024 <- pp2024 %>%
  mutate(RegulatedEntityName = ifelse(
    RegulatedEntityName =="Co-operative Party", "Labour Party", RegulatedEntityName
  ))

# Remove £ sign and convert to numeric
pp2024$Value <- as.numeric(gsub("[£,\"]", "", pp2024$Value))

#keep only relevant columns

pp2024 <- pp2024 %>%
  select(RegulatedEntityName, ReportingPeriodName, ReceivedDate, Value, DonorStatus, DonorName)

# changing names of parties

pp2024$RegulatedEntityName <- gsub("Conservative and Unionist Party", "Conservative Party", pp2024$RegulatedEntityName)
pp2024$RegulatedEntityName <- gsub("Scottish National Party \\(SNP\\)", "SNP", pp2024$RegulatedEntityName)

#creating factors

pp2024$RegulatedEntityName <- factor(pp2024$RegulatedEntityName, levels = c("Conservative Party", "Labour Party", "Liberal Democrats", "Reform UK", "SNP", "Green Party", "Climate Party", "Social Democratic Party"))
 
pp2024$DonorStatus <- factor(pp2024$DonorStatus, levels = c("Individual", "Company", "Trade Union", "Unincorporated Association", "Friendly Society"))

pp2024$ReportingPeriodName <- factor(pp2024$ReportingPeriodName, levels = c("Pre-Poll 1 - Party(30/05/24 - 05/06/24) UKPGE 2024", "Pre-Poll 2 - Party(06/06/24 - 12/06/24) UKPGE 2024"))

```

```{r include=FALSE}

# Define all possible levels for DonorStatus and ReportingPeriodName
donor_statuses <- c('Individual', 'Company', 'Trade Union', 'Unincorporated Association', 'Friendly Society')
reporting_periods <- c('Pre-Poll 1 - Party(30/05/24 - 05/06/24) UKPGE 2024', 'Pre-Poll 2 - Party(06/06/24 - 12/06/24) UKPGE 2024')

# Create a complete grid of all combinations
all_combinations <- expand.grid(
  RegulatedEntityName = unique(pp2024$RegulatedEntityName),
  ReportingPeriodName = reporting_periods,
  DonorStatus = donor_statuses,
  stringsAsFactors = FALSE
)

# Merge with the original data to ensure all combinations are present
pp2024_complete <- all_combinations %>%
  left_join(pp2024, by = c("RegulatedEntityName", "ReportingPeriodName", "DonorStatus")) %>%
  mutate(Value = ifelse(is.na(Value), 0, Value))

# creating a table split by week and sum received by each party

pp_w1w2 <- pp2024_complete %>%
  group_by(RegulatedEntityName, ReportingPeriodName, DonorStatus) %>%
  summarise(Total = sum(Value), .groups = 'drop') %>%
  unite("DonorStatus_ReportingPeriodName", DonorStatus, ReportingPeriodName) %>%
  pivot_wider(names_from = DonorStatus_ReportingPeriodName, values_from = Total, values_fill = list(Total = 0))

# Summarise and reshape the data
pp_w1w2 <- pp2024_complete %>%
  group_by(RegulatedEntityName, ReportingPeriodName, DonorStatus) %>%
  summarise(Total = sum(Value), .groups = 'drop') %>%
  unite("DonorStatus_ReportingPeriodName", DonorStatus, ReportingPeriodName) %>%
  pivot_wider(names_from = DonorStatus_ReportingPeriodName, values_from = Total, values_fill = list(Total = 0))

# redo column order

pp_w1w2 <- pp_w1w2 %>%
  select(RegulatedEntityName, `Individual_Pre-Poll 1 - Party(30/05/24 - 05/06/24) UKPGE 2024`, `Individual_Pre-Poll 2 - Party(06/06/24 - 12/06/24) UKPGE 2024`, `Company_Pre-Poll 1 - Party(30/05/24 - 05/06/24) UKPGE 2024`, `Company_Pre-Poll 2 - Party(06/06/24 - 12/06/24) UKPGE 2024`, `Trade Union_Pre-Poll 1 - Party(30/05/24 - 05/06/24) UKPGE 2024`, `Trade Union_Pre-Poll 2 - Party(06/06/24 - 12/06/24) UKPGE 2024`, `Unincorporated Association_Pre-Poll 1 - Party(30/05/24 - 05/06/24) UKPGE 2024`, `Unincorporated Association_Pre-Poll 2 - Party(06/06/24 - 12/06/24) UKPGE 2024`, `Friendly Society_Pre-Poll 1 - Party(30/05/24 - 05/06/24) UKPGE 2024`, `Friendly Society_Pre-Poll 2 - Party(06/06/24 - 12/06/24) UKPGE 2024`)

```

```{r echo=FALSE}

# Format numbers as whole numbers with £ sign and remove decimal places
pp_w1w2 <- pp_w1w2 %>%
  mutate(across(-RegulatedEntityName, ~paste0("£", format(round(., 0), big.mark = ",", scientific = FALSE))))

# Compute row totals
pp_w1w2 <- pp_w1w2 %>%
  mutate(Total = rowSums(across(where(is.character), ~ as.numeric(gsub("[£,]", "", .))), na.rm = TRUE)) %>%
  mutate(Total = sprintf("£%s", format(Total, big.mark = ",", scientific = FALSE)))

# Compute column totals
column_totals <- pp_w1w2 %>%
  summarise(across(where(is.character), ~ sum(as.numeric(gsub("[£,]", "", .)), na.rm = TRUE))) %>%
  mutate(RegulatedEntityName = "Total") %>%
  mutate(across(where(is.numeric), ~ sprintf("£%s", format(.x, big.mark = ",", scientific = FALSE))))

# Bind column totals to the original table
pp_w1w2 <- bind_rows(pp_w1w2, column_totals)

# Convert the "Total" column to character to match other columns
pp_w1w2 <- pp_w1w2 %>%
  mutate(across(where(is.numeric), as.character))

# Remove blank spaces in column names
pp_w1w2 <- remove_spaces(pp_w1w2)

# Ensure the number of column names matches the actual number of columns
col_names <- c("Party", rep(c("W1", "W2"), times = 5), "Total")

# Summary table
pp_w1w2 %>%
  kable("html", col.names = col_names, align = 'c') %>%
  add_header_above(c(" " = 1, "Individual" = 2, "Company" = 2, "Trade Union" = 2, "Unincorporated Association" = 2, "Friendly Society" = 2, "Total" = 1)) %>%
  kable_styling(full_width = F)

```

### 2024 totals: combined

```{r include=FALSE}

#breaking down by party and donor status

# Create a complete data frame with all combinations of Party Name and Donor Status

total_prepoll <- expand.grid(RegulatedEntityName = 
                            levels(pp2024$RegulatedEntityName), 
                         DonorStatus = 
                           unique(pp2024$DonorStatus)
                         )

# merge the values with each combo

prepoll_table <- total_prepoll %>%
  left_join(pp2024 %>%
              group_by(RegulatedEntityName, DonorStatus) %>%
            summarise(TotalValue = sum(Value, na.rm = TRUE), 
                      .groups = 'drop'),
            by = c("RegulatedEntityName", "DonorStatus"))

prepoll_table$TotalValue[is.na(prepoll_table$TotalValue)] <- 0

#Convert value to money format

prepoll_table$TotalValue <- round(prepoll_table$TotalValue)
prepoll_table$TotalValue <- sprintf("£%s", format(prepoll_table$TotalValue, big.mark = ",", scientific = FALSE))

#convert to a wide format

prepoll_table <- prepoll_table %>%
  pivot_wider(names_from = DonorStatus,
              values_from = TotalValue)

```

```{r echo=FALSE}
# Compute row totals
prepoll_table <- prepoll_table %>%
  mutate(Total = rowSums(across(where(is.character), ~ as.numeric(gsub("[£,]", "", .))), na.rm = TRUE)) %>%
  mutate(Total = sprintf("£%s", format(Total, big.mark = ",", scientific = FALSE)))

# Compute column totals
column_totals <- prepoll_table %>%
  summarise(across(where(is.character), ~ sum(as.numeric(gsub("[£,]", "", .)), na.rm = TRUE))) %>%
  mutate(RegulatedEntityName = "Total") %>%
  mutate(across(where(is.numeric), ~ sprintf("£%s", format(.x, big.mark = ",", scientific = FALSE))))

# Bind column totals to the original table
prepoll_table <- bind_rows(prepoll_table, column_totals)

# Convert the "Total" column to character to match other columns
prepoll_table <- prepoll_table %>%
  mutate(across(where(is.numeric), as.character))

# Replace 'unincorporated association' with 'unincorporated<br>association' in the column names
names(prepoll_table) <- gsub("Unincorporated Association", "Unincorporated<br>Association", names(prepoll_table))

# Remove the first column title
names(prepoll_table)[1] <- ""

# Use kable to create a nicely formatted table
kable(prepoll_table, format = "html", escape = FALSE, table.attr = "style='width:100%;'", align = c("l", rep("c", ncol(prepoll_table) - 1))) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"), full_width = FALSE) %>%
  column_spec(1, bold = TRUE) %>%
  row_spec(nrow(prepoll_table), bold = TRUE, color = "white", background = "black") %>%
  footnote(general = "Donations made to the Co-operative party were combined with the Labour Party.", 
           general_title = "Note: ", 
           footnote_as_chunk = TRUE,
           threeparttable = T) %>%
  add_header_above(c(" " = 1, "Donor Status" = ncol(prepoll_table) - 1), bold = TRUE) %>%
row_spec(0, align = "center")

```

### 2019 comparison 

#### Totals: week one

```{r include=FALSE}

pp2019 <- read.csv("data2019/alldonations_2019.csv")
pp2024 <- read.csv("data2024/prepoll1_2024.csv")

# getting 2024 back into correct format

#combining the Labour and Cooperative party

pp2024 <- pp2024 %>%
  mutate(RegulatedEntityName = ifelse(
    RegulatedEntityName =="Co-operative Party", "Labour Party", RegulatedEntityName
  ))

# filtering pre-poll week 1

pp2019 <- pp2019 %>%
  filter(ReportingPeriodName == "Pre-Poll 1 - Party(06/11/19 - 12/11/19) UKPGE 2019")

#bind the tables together for comparisons

ppw1 <- rbind(pp2019, pp2024)

#keep only relevant columns

ppw1 <- ppw1 %>%
  select(RegulatedEntityName, ReportingPeriodName, ReceivedDate, Value, DonorStatus, DonorName)

# removing public funds

ppw1 <- ppw1 %>%
  filter(!DonorStatus == "Public Fund")

# Remove £ sign and convert to numeric to make candidates
ppw1$Value <- as.numeric(gsub("[£,\"]", "", ppw1$Value))

# converting names

ppw1$RegulatedEntityName <- gsub("Conservative and Unionist Party", "Conservative Party", ppw1$RegulatedEntityName)
ppw1$RegulatedEntityName <- gsub("Scottish National Party \\(SNP\\)", "SNP", ppw1$RegulatedEntityName)
ppw1$RegulatedEntityName <- gsub("Alliance - Alliance Party of Northern Ireland", "Alliance", ppw1$RegulatedEntityName)

```

```{r echo=FALSE}

# compare total donated to each party 

#creating factors

ppw1$RegulatedEntityName <- factor(ppw1$RegulatedEntityName, levels = c("Conservative Party", "Labour Party", "Liberal Democrats", "Reform UK", "SNP", "Green Party", "Climate Party", "Social Democratic Party", "Alliance"))

ppw1$DonorStatus <- factor(ppw1$DonorStatus, levels = c("Individual", "Company", "Trade Union", "Unincorporated Association", "Friendly Society"))

ppw1$ReportingPeriodName <- factor(ppw1$ReportingPeriodName, levels = c("Pre-Poll 1 - Party(06/11/19 - 12/11/19) UKPGE 2019", "Pre-Poll 1 - Party(30/05/24 - 05/06/24) UKPGE 2024"))

# Create a complete data frame with all combinations of Party Name and pre-poll period

pp_comparison <- expand.grid(RegulatedEntityName = 
                            levels(ppw1$RegulatedEntityName), 
                         ReportingPeriodName = 
                           unique(ppw1$ReportingPeriodName)
                         )

# merge the values with each combo

prepoll_comparison <- pp_comparison %>%
  left_join(ppw1 %>%
              group_by(RegulatedEntityName, ReportingPeriodName) %>%
            summarise(TotalValue = sum(Value, na.rm = TRUE), 
                      .groups = 'drop'),
            by = c("RegulatedEntityName", "ReportingPeriodName"))

prepoll_comparison$TotalValue[is.na(prepoll_comparison$TotalValue)] <- 0

#Convert value to money format

prepoll_comparison$TotalValue <- round(prepoll_comparison$TotalValue)
prepoll_comparison$TotalValue <- sprintf("£%s", format(prepoll_comparison$TotalValue, big.mark = ",", scientific = FALSE))

#convert to a wide format

prepoll_comparison <- prepoll_comparison %>%
  pivot_wider(names_from = ReportingPeriodName,
              values_from = TotalValue)

#rename column names

prepoll_comparison <- prepoll_comparison %>%
  rename(`Week 1 2019` = `Pre-Poll 1 - Party(06/11/19 - 12/11/19) UKPGE 2019`,
         `Week 1 2024` = `Pre-Poll 1 - Party(30/05/24 - 05/06/24) UKPGE 2024`)

# Calculate column totals
column_totals <- prepoll_comparison %>%
  summarise(across(where(is.character), ~ sprintf("£%s", format(sum(as.numeric(gsub("[£,]", "", .))), big.mark = ",", scientific = FALSE)))) %>%
  mutate(RegulatedEntityName = "Total")

# Bind the totals row to the original table
prepoll_comparison <- bind_rows(prepoll_comparison, column_totals)

# format table

totals_comparison <- kable(prepoll_comparison, col.names = c("", "2019", "2024")) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"), full_width = FALSE) %>%
  add_header_above(c(" " = 1, "Week One" = 2)) %>%
  row_spec(nrow(prepoll_comparison), bold = TRUE, color = "white", background = "black") %>%
  row_spec(0, align = "center")

```

```{r, echo=FALSE}

totals_comparison

```

#### Split by donor type

```{r echo=FALSE, warning=FALSE}

year_summary <- ppw1 %>%
  select(RegulatedEntityName, ReportingPeriodName, DonorStatus, Value) %>%
  group_by(RegulatedEntityName, DonorStatus, ReportingPeriodName) %>%
  summarise(TotalValue = sum(Value), .groups = 'drop') %>%
  complete(RegulatedEntityName, DonorStatus, ReportingPeriodName, fill = list(TotalValue = 0))

# Convert value to money format
year_summary$TotalValue <- round(year_summary$TotalValue)
year_summary$TotalValue <- sprintf("£%s", format(year_summary$TotalValue, big.mark = ",", scientific = FALSE))

# create wide format 

year_summary_wide <- year_summary %>%
  pivot_wider(
    names_from = c(DonorStatus, ReportingPeriodName),
    values_from = TotalValue,
    names_sep = "_"
  )

# Calculate column totals

column_total <- year_summary_wide %>%
  summarise(across(everything(), ~ sum(as.numeric(gsub("[£,]", "", .)),
                                       na.rm = TRUE))) %>%
  mutate(RegulatedEntityName = "Total") %>%
  mutate(across(-RegulatedEntityName, ~ sprintf("£%s", format(.x, big.mark = ",", scientific = FALSE))))

# remove blank spaces function

year_summary_wide <- remove_spaces(year_summary_wide)

# use replace_pound_zero function to make a neater table

year_summary_wide <- replace_pound_zero(year_summary_wide)

# bind the new row with original dataframe

year_summary_wide <- rbind(year_summary_wide, column_total)

```

```{r echo=FALSE}

# Replace 'unincorporated association' with 'unincorporated<br>association' in the column names
names(year_summary_wide) <- gsub("Unincorporated Association", "Unincorporated<br>Association", names(year_summary_wide))

# Remove the first column title
names(year_summary_wide)[1] <- ""

#create kable table

kable(year_summary_wide, col.names = c("", "2019", "2024", "2019", "2024", "2019", "2024", "2019", "2024", "2019", "2024")) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"), full_width = FALSE) %>%
  add_header_above(c(" " = 1, "Individual" = 2, "Company" = 2, "Trade Union" = 2, "Unincorporated Association" = 2, "Friendly Society" = 2)) %>%
  row_spec(nrow(year_summary_wide), bold = TRUE, color = "white", background = "black") %>%
  row_spec(0, align = "center")


```

### Week 2: 2024

```{r}

prepoll2 <- read.csv("data2024/prepoll2_2024.csv")

```


### Labour and Conservative comparison

```{r include=FALSE}

ppw1 <- ppw1 %>%
  filter(RegulatedEntityName == "Conservative Party"|
         RegulatedEntityName == "Labour Party")

# this leave 111 donations

# Create the bar chart
ggplot(ppw1, aes(x = interaction(RegulatedEntityName, ReportingPeriodName), y = Value, fill = DonorStatus)) +
  geom_bar(stat = "identity") +
  labs(x = "Party and Year", y = "Total Amount Donated", fill = "DonorStatus") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_fill_brewer(palette = "Set3")

```

