---
title: "Candidate Names"
---

### Creating a new csv file with a tally for each time the name occurs in the data

```{r}

library(tidyverse)

#Data source: democracy club, candidate list, released 07/06/2024

name <- read.csv("candidate_name/candidate_GE24.csv")

```

```{r}

#replace captain beany with name

name$person_name <- sub("Captain Beany", "Barry Kirk", name$person_name, fixed = TRUE)

name$person_name <- sub("The Zok", "Zoran Zoc", name$person_name, fixed = TRUE)

#tally first names

first_name_tally <- name %>%
  mutate(cleaned_names = gsub("Sir |Lord |Doctor |Dr |M. ", "", person_name)) %>% 
  mutate(first_name = sub(" .*", "", cleaned_names)) %>%  
  count(first_name, sort = TRUE)  

#create a new column with all lower case

first_name_tally <- first_name_tally %>%
  mutate(name_lower = tolower(first_name))

#some anomalies: monster raving loony party, AI steve, empororor of india prince

```

```{r}

name_tally <- name %>%
  filter(grepl("^Bridget ", person_name)) %>%  
  group_by(party_name) %>%  # Group by party_name
  summarise(count = n())  # Count occurrences


# split up first name and last name into new column

name <- name %>%
  select(person_name, party_name, post_label) %>%
  mutate(cleaned_names = gsub("Sir |Lord |Doctor |Dr |M. ", "", person_name)) %>% 
  mutate(first_name = sub(" .*", "", cleaned_names),
         last_name = str_extract(cleaned_names, "\\w+$")) %>%
  select(person_name, first_name, last_name, party_name, post_label)

# Combine Labour and the cooperative party into 1


# male, female and unknown names matched

male_names1 <- c("David", "John", "Paul", "James", "Mark", "Andrew", "Richard", "Michael", "Ian", "Stephen", "Steve", "Peter", "Simon", "Robert", "Tom", "Ben", "Jonathan", "Andy", "Matthew", "Mike", "Martin", "Neil", "Tony", "Dan", "Daniel", "Christopher", "Jack", "Matt", "Tim", "Adam", "Graham", "Alan", "Craig", "Luke", "Edward", "Gary", "Nigel")

male_names2 <- c("Gareth", "Darren", "Scott", "Stuart", "Thomas", "Oliver", "Rob", "Bill", "Jason", "Kevin", "Nicholas", "Dave", "George", "Jim", "Josh", "Keith", "Mohammed", "Barry", "Jeremy", "Brian", "Charles", "Colin", "Philip", "Alexander", "Anthony", "Bob", "Ed", "Guy", "Henry", "Pete", "Phil", "Roger", "Will", "William", "Jon", "Liam", "Patrick", "Stewart", "Shaun", "Trevor", "Alastair", "Dominic", "Frank", "Gavin", "Iain", "Jacob", "Jake", "Jeff", "Karl", "Malcolm", "Steven", "Adrian", "Damian", "Joshua", "Khalid", "Kieran", "Marcus", "Alistair", "Callum", "Carl", "Clive", "Declan", "Donald", "Duncan", "Gordon", "Grant", "Greg", "Hamish", "Harry", "Lewis", "Martyn", "Owen", "Samuel", "Tommy", "Benjamin", "Brandon", "Brendan", "Connor", "Derek", "Geoff", "Gregory", "Joseph")

male_names3 <- c("Marc", "Raj", "Toby", "Abdul", "Arnold", "Bernard", "Bradley", "Douglas", "Dylan", "Eddie", "Freddie", "Garry", "Glen", "Imran", "Johnny", "Justin", "Keir", "Kenneth", "Laurence", "Leo", "Mick", "Muhammad", "Nathan", "Niall", "Robbie", "Rupert", "Timothy", "Amir", "Angus", "Antonio", "Arthur", "Bobby", "Brent", "Brett", "Conor", "Conrad", "Damien", "Darryl", "Dean", "Desmond", "Doug", "Earl", "Edmund", "Edwin", "Eric", "Ethan", "Geoffrey", "Gerald", "Glenn", "Grahame", "Howard", "Hugo", "Joel", "Jordan", "Ken", "Khalil", "Kieron", "Kyle", "Lawrence", "Louie", "Mathew", "Mohamed", "Mohammad", "Muhammed", "Naveed", "Norman", "Oscar", "Phillip", "Raymond", "Rich", "Rod", "Ron", "Roy", "Russ", "Seamus", "Sebastian", "Shane", "Theo", "Victor", "Wayne", "Wesley", "Ahmed", "Aidan", "Alasdair", "Alberto", "Alfred", "A.", "AI", "Aadil", "Abbas", "Abdoul", "Abdulla", "Abul", "Ade", "Adedotun", "Afzal", "Ahmet", "Ahsan", "Ajaz", "Ajmal", "Akeel", "Akhlaque", "Akhmed", "Al")

male_names4 <- c("Aled", "Alexi", "AliRom", "Allister", "Altaf", "Alun", "Alyn", "Ameet", "Amjad", "Ammar", "Amrit", "Andre", "Andrei", "Anil", "Anwarul", "Archibald", "Arnie", "Arran", "Arron", "Asa", "Ashvir", "Athar", "Atif", "Attic", "Attiq", "Aubrey", "Audel", "Augustine", "Austin", "Ayoub", "Azhar", "Azmat", "Babar", "Baggy", "Bambos", "Barmy", "Barney", "Baron", "Bart", "Bastôn", "Bayo", "Benedict", "Benet", "Bim", "Blair", "Blaise", "Blake", "Brad", "Brenden", "Bret", "Brook", "Bruce", "Byron", "Cade", "Cahal", "Calum", "Calvin", "Cam", "Carlo", "Carne", "Cas", "Cathal", "Caz", "Chan", "Charith", "Chas", "Chaz", "Ciaran", "Citizen", "Clayton", "Cliff", "Cole", "Collan", "Colum", "Count", "Cris", "Crispian", "Dafydd", "Dai", "Dale", "Damon", "Darshan", "Daud", "Davinder", "Dawud", "Debojyoti", "Denis", "Dennis", "Des", "Dharmanand", "Dhruv", "Dhruva", "Dick", "Dickie", "Dillan", "Dino", "Dipesh", "Dom", "Dominick", "Donal", "Donnie", "Draeyk", "Drummond", "Dáire", "Ehtashamul", "Ejel", "Elliott", "Ellis", "Emmett", "Emperor", "Eraj", "Erik", "Ertan", "Eugene", "Ewan", "Ezechiel", "Fabian", "Fabio", "Faisal", "Faraz", "Farooq", "Fergal", "Fesl", "Filson", "Franck", "Fred")

male_names5 <- c("Frederick", "Gagan", "Garreth", "Ged", "Gerard", "Gez", "Ghazi", "Giane", "Gideon", "Giles", "Giuseppe", "Glyn", "Gregor", "Grumpus", "Gulvinder", "Gurinder", "Gus", "Gwenton", "Gwyn", "Habib", "Hamilton", "Hans", "Harbant", "Hari", "Haroun", "Harrison", "Hassan", "Heiko", "Helmi", "Hersh", "Hoo-Ray", "Horatio", "Howling", "Huge", "Iconic", "Iddrisu", "Ieuan", "Iftikhar", "Imad", "Imtiaz", "Ioan", "Iolo", "Iqbal", "Irakli", "Irfan", "Irwen", "Isaac", "Ishtiaq", "Issan", "Ivan", "Jackson", "Jag", "Jaginder", "Jahir", "Jamal", "Jamie-Lee", "Janus", "Javed", "Jed", "Jeevun", "Jeffrey", "Jehad", "Jenner", "Jerome", "Jerry", "Jesse", "Job", "Jody", "Johnathan", "Johno", "Jonathon", "Jonny", "Josiah", "Jovan", "Kabeer", "Kaine", "Kamel", "Kamran", "Kane", "Kanishka", "Kashif", "Kayode", "Kaz", "Kefentse", "Keiron", "Kelvin", "Ketankumar", "Kevan", "Khandu", "Kieren", "King", "Kiran", "Kit", "Knigel", "Korin", "Kuldev", "Kwaku", "Kyn", "Lalit", "Lance", "Larry", "Lars", "Laurent", "Laurie", "Lenny", "Leslie", "Lester", "Lincoln", "Lionel", "Lloyd", "Lorenzo", "Louis", "Lucas", "Lucian", "Luigi", "Lynden", "Maciej", "Mal", "Malachy", "Mamun", "Manny", "Manu", "Maqsood", "Marco", "Markus", "Mattie", "Matty", "Maurice", "Maxwell", "Mayuran", "Mehmood", "Merv", "Mian", "Michal", "Miles", "Minhajul", "Mitchell", "Mocky", "Mohhamed", "Monty", "Moui-Tabrizy", "Mustafa", "Mustaque", "Muzafar", "Myles", "Nagarjun", "Nagender", "Nahim", "Najmul", "Narinder", "Nasri", "Navdeep", "Navendu", "Navid", "Neale", "Neill", "Neville", "Niel", "Nimal", "Nisar", "Nizam", "Noah", "Nurul", "Obi", "Olivio", "Olli", "Ollie", "Olusola", "Omar")

male_names6 <- c("Osman", "Otto", "Owain", "Owais", "Paco", "Padraic", "Parham", "Parmjit", "Pedro", "Pelé", "Perran", "Pierce", "Piers", "Prabhdeep", "Prad", "Praful", "Primesh")

#FEMALE

female_names1 <- c("Sarah", "Helen", "Catherine", "Rachel", "Emma", "Claire", "Caroline", "Kate", "Laura", "Rebecca", "Lucy", "Amanda", "Jane", "Anna", "Hannah", "Julie", "Ruth", "Elizabeth", "Louise", "Karen", "Alison", "Angela", "Anne", "Jennifer", "Liz", "Maria", "Emily", "Joanna", "Lisa", "Sally", "Charlotte", "Christine", "Clare", "Debbie", "Julia", "Mary", "Susan", "Ann", "Jan", "Kim", "Lauren", "Pippa", "Rosie", "Vicky", "Victoria", "Wendy", "Cat", "Diana", "Elaine", "Fiona", "Jessica", "Katherine", "Katie", "Linda", "Lorraine", "Lynn", "Maureen", "Melanie", "Natalie", "Alexandra", "Amy", "Andrea", "Becca", "Carol", "Dawn", "Denise", "Ellie", "Gillian", "Heather", "Hilary", "Jayne", "Jill", "Kelly", "Lorna", "Michelle", "Pamela", "Patricia", "Samantha", "Sandra", "Sara","Sophie", "Sue", "Teresa", "Vanessa", "Yvonne", "Alice", "Amelia", "Angie", "Bridget", "Carla", "Christina", "Donna", "Georgie", "Helena", "Holly", "Jackie", "Jade", "Janet", "Janice", "Jenny", "Joy", "Katharine", "Kirsty", "Lara", "Margaret", "Marie", "Maxine", "Nadia", "Nancy", "Natasha", "Nicola", "Pauline", "Rachael", "Stephanie", "Vicki", "Yasmin", "Aisha", "Anita", "Anne-Marie", "Anneliese", "Annie", "Becky", "Caitlin")

female_names2 <- c("Cara", "Carolyn", "Celia", "Christie", "Danielle", "Deborah", "Deirdre", "Diane", "Eleanor", "Erin", "Esther", "Eva", "Fay", "Fionna", "Gemma", "Georgia", "Georgina", "Gina", "Gloria", "Harriet", "Hazel", "Imogen", "Irene", "Isobel", "Izzy", "Jacqueline", "Jemma", "Jen", "Judith", "Judy", "June", "Kathleen", "Kathryn", "Kayleigh", "Kiera", "Leanne", "Lizzie", "Lois", "Lyn", "Lynda", "Maggie", "Marianne", "Maya", "Mona", "Monica", "Olivia", "Paula", "Penelope", "Penny", "Phoebe", "Rowena", "Sharon", "Sheila", "Shona", "Siobhan", "Sonia", "Sophia", "Stella", "Suzanne", "Tessa", "Thérèse", "Zoe", "Aarti", "Abigail", "Adele", "Alicia", "Alixandra", "Allison", "Aasha", "Aasiya", "Abena", "Abi", "Abtisam", "Adria", "Aheesha", "Aishat", "Albati", "Amie", "Ammi", "Ange", "Angeliki", "Ani", "Anja", "Anna-Maria", "Annaliese", "Annette", "Antoinette", "Antonia", "Anum", "Aphra", "April", "Apsana", "Aroma", "Aruhan", "Asha", "Ayesha", "Barbara", "Beatrice", "Beccy", "Bell", "Bella", "Bernadette", "Beth", "Bianca", "Brenda", "Cadewyn", "Caitriona", "Candice", "Carissma", "Carline", "Carolyne", "Carolynn", "Caron", "Cassi", "Cassie", "Cate", "Cath", "Cathy", "Chantal", "Charley", "Charmaine", "Chelsea", "Chelsey", "Cheney", "Cherilyn", "Cheryl", "Cheryl-Ann", "Chi", "Chika", "Chipiliro", "Chloe", "Chloe-Jane", "Chloe-Louise", "Chrishni", "Clareine", "Claudia", "Colette", "Cordelia", "Corinthia", "Corri", "Daisy", "Damola", "Danni", "Danuta", "Deanna", "Debra", "Deidre", "Desi", "Devenne", "Devina", "Dine", "Dionne", "Dominie", "Déirdre", "Eishar", "Ekua", "Ellen", "Elsie", "Emma-Jane", "Emmie", "Ese", "Esme")

female_names3 <- c("Eunice", "Evelyn", "Faiza", "Farzana", "Faten", "Faye", "Felicity", "Fennie", "Feryal", "Fleur", "Flick", "Flo", "Florence", "Francesca", "Francoise", "Freya", "Gabrielle", "Gail", "Gayathri", "Gemma-Jane", "Gen", "Geraldine", "Gerri", "Giovanna", "Gurpreet", "Hajira", "Halima", "Hanna", "Harpreet", "Harriett", "Hayley", "Heidi", "Hema", "Hillary", "Hina", "Holly-Mae", "Irenea", "Isabel", "Isabella", "Isabelle", "Issy", "Ivana", "Jabu", "Jacqui", "Jamila", "Janey", "Jaswinder", "Javeria", "Jeannine", "Jenifer", "Jessie", "Jilleane", "Joan", "Joani", "Joanne", "Jodie", "Johanna", "Josie", "Ju", "Juliet", "Justine", "Kamala", "Kamla", "Karin", "Kathrine", "Kathy", "Katrina", "Katy", "Kelda", "Kellie-Jay", "Kemi", "Khalila", "Khobi", "Kirith", "Kirsteen", "Kirsten", "Kristy", "Kulsum", "Lady", "Laura-Beth", "Laura-Louise", "Layla", "Leena", "Leila", "Lex", "Leyla", "Leza", "Lia", "Lilian", "Lillian", "Linsey", "Lizzi", "Llinos", "Lola", "Lynne", "Maahwish", "Maddison", "Magdaline", "Mahtab", "Malihah", "Manda", "Mandy", "Manuela", "Marian", "Marianna", "Marie-Clair", "Marilyn", "Marion", "Marisa", "Marsha", "Martha", "Maryse", "Mehmoona", "Mehreen", "Mhairi", "Miatta", "Mims", "Miranda", "Miriam", "Moira", "Momtaz", "Moni", "Morgan", "Munira", "Muryam", "Nada", "Nanda", "Nandita", "Naomi", "Naranee", "Nariese", "Natalia", "Nataly", "Nathalie", "Naushabah", "Neena", "Nesil", "Netty", "Nia", "Niamh", "Nicky", "Nida", "Noor", "Nora", "Nuala", "Nupur", "Nus")

female_names4 <- c("Oana", "Onike", "Oyebola", "Pallavi", "Pam", "Paras", "Paulette", "Pavitar", "Peggy", "Perveen", "Petra", "Philippa", "Pinder", "Polly", "Poppy", "Preet", "Priti")

non_binary <- c()

other <- c("A.N.ON", "Adie", "Akshay", "Amer", "Anni", "Athol", "Aysha", "Baz", "Bex", "Bharatkumar", "Binka", "Dee", "Gwen", "Harl", "Hoz", "Kombat", "Mariatu", "Morven", "Mykel", "Nagbea")

#matching the names 

gender_check <- name %>%
  mutate(gender = case_when(
    first_name %in% male_names1 ~ "men",
    first_name %in% male_names2 ~ "men",
    first_name %in% male_names3 ~ "men",
    first_name %in% male_names4 ~ "men",
    first_name %in% male_names5 ~ "men",
    first_name %in% female_names1 ~ "women",
    first_name %in% female_names2 ~ "women",
    first_name %in% female_names3 ~ "women",
    first_name %in% non_binary ~ "non-binary/third gender",
    first_name %in% other ~ "unknown",
    TRUE ~ ""
  ))


#unisex names ordered separately




#adding in the YouGov poll of most likely to get the seat


```

